### ISSUE TITLE
Link transition time causes text to appear after filter menu has closed.

### ISSUE THREAD

**Issue by brizee** [opentexts/opentexts#109]
![opentexts_filtertext_bug](https://user-images.githubusercontent.com/188324/91662162-6d8cc900-ead8-11ea-9ab1-ca8f45428d5a.gif)

The introduction of transitions for links in #108 seems to have caused the links in filter menus to remain as an overlay when the background div has already become invisible.

**Comment by sarahmonster** [comment]
Good call! I started trying to look into this and some other filtering issues, but I'm finding the filters don't work for me locally:

![2020-09-10 22 34 25](https://user-images.githubusercontent.com/376315/92810927-e4b63d00-f3b5-11ea-920b-750cb716e438.gif)

I tried in two different browsers but kept getting the same result. 😭 Would you have any idea what might be causing this? It seems to be working fine on the staging site...
