### ISSUE TITLE
Introduce data to support a 'year' filter

### ISSUE THREAD

**Issue by stuartlewis** [opentexts/opentexts#119]
As discussed previously, it would be great to add a year filter to help find materials from a certain date range or year.

I prospose a few steps, which will also mean we don't break the curent site as this will require changes to the solr scheme:

- [x] Create a new solr core 'otw-v2'
- [x] Add a new solr field called 'date'. This would be a string and can contain any value and be used for display purposes
- [x] Remove the current year field (a string)
- [x] Add a new year field (integer)
- [x] Add a new year_facet field copying from the year field
- [x] Reload all the data into the new core, with the new year field, ensuring it is always a four digital number (\d{4}$) (this could take a week or two)
- [x] Add a new year filter. See [half way down this web page](https://tech.findmypast.com/solr-facets/) (a local Dundee company @brizee!) for ideas of how to use the 'range' option to to show the filter in varying granularities (e.g. centuries -> decades -> years): to be completed in issue #78 

Does that sound OK @brizee? If so, I'll get cracking!

Data to reload:

- [x] Bodleian Library
- [x] National Library of Scotland
- [x] National Library of Wales
- [x] Wellcome Collection
- [x] DigitalNZ
- [x] HathiTrust
- [x] Internet Archive
- [x] QUB

**Comment by brizee** [comment]
Yep, this all makes sense to me - nice seamless migration plan too

**Comment by stuartlewis** [comment]
Hmmmm - step 2 requires a complete reindex, and it doesn't seem possible to force an internal solr reindex (like is possible with a traditional SQL database). The way to do this is to reload data which will ensure it is indexed. This will require a modified plan...

I'll create a new empty solr core. The current one is called otw, so lets call this otw-v2. I'll point the staging server to this new core so we can test it. Once it is built and working, we just [reconfigure the production copy to read from the new core](https://github.com/opentexts/opentexts/blob/main/app/Config/Solr.php#L13)

**Comment by brizee** [comment]
/sigh nothing's ever easy is it? :smile:

If this becomes a recurring thing I'm lobbying for the cores to be called [otw-blue and otw-green](https://martinfowler.com/bliki/BlueGreenDeployment.html) 😁

**Comment by stuartlewis** [comment]
...or we treat solr as an API (which it is, anyway), and [semantically version it](https://semver.org/) so we know what is / is not backwards compatible. Overtime the solr scheme needs to be very stable,  as re-indexing all data will get harder and harder as it grows.

**Comment by brizee** [comment]
hmm yeah that makes sense with the url structure - I assume we'd still be wiping older versions pretty regularly though? 😄

**Comment by stuartlewis** [comment]
Yeah - in some ways its a bit moot, as the production (and staging) applications are (currently) the only users of the solr cores - so perhaps your blue/green is the easiest?!

**Comment by brizee** [comment]
Hopefully we never have to do a significant rollback of code (can't see why we would in a readonly app) but semver could be pretty useful in that case to be fair - might be a case of better to have and not need it than need it and not have it?

**Comment by stuartlewis** [comment]
This now works, for example see: [http://opentexts.world:8983/solr/otw-v2/select?facet.range=year&facet.range.start=1000&facet.range.end=2050&facet.range.gap=100&facet=on&q=*%3A*&rows=0](http://opentexts.world:8983/solr/otw-v2/select?facet.range=year&facet.range.start=1000&facet.range.end=2050&facet.range.gap=100&facet=on&q=*%3A*&rows=0)

```json
{
  "responseHeader":{
    "zkConnected":true,
    "status":0,
    "QTime":19,
    "params":{
      "facet.range":"year",
      "q":"*:*",
      "facet.range.gap":"100",
      "rows":"0",
      "facet":"on",
      "facet.range.start":"1000",
      "facet.range.end":"2050"}},
  "response":{"numFound":231088,"start":0,"maxScore":1.0,"numFoundExact":true,"docs":[]
  },
  "facet_counts":{
    "facet_queries":{},
    "facet_fields":{},
    "facet_ranges":{
      "year":{
        "counts":[
          "1000",8,
          "1100",11,
          "1200",271,
          "1300",238,
          "1400",5,
          "1500",83,
          "1600",2756,
          "1700",27996,
          "1800",181154,
          "1900",13189,
          "2000",5],
        "gap":100,
        "start":1000,
        "end":2100}},
    "facet_intervals":{},
    "facet_heatmaps":{}}}
```

(Note some anomalies in the years, e.g. where year = '1000'. This is bad data processing on my part, so I need to go and figure out what's cuasing that and re-process then re-imort the data from Oxford.)

I've updated the [staging site](https://design.opentexts.world/search) to use the new otw-v2 solr core so we can test there.

**Comment by sarahmonster** [comment]
There's a proposed design for this in #78, which (I think!) is effectively a duplicate issue, unless I'm misunderstanding the intent here. 🙂

**Comment by stuartlewis** [comment]
> There's a proposed design for this in #78, which (I think!) is effectively a duplicate issue, unless I'm misunderstanding the intent here. 🙂

I've changed the title to clarify this issue (which is now complete). This is the work behind the scenes to load the data so we have a new numeric field that we can use for year filtering.

There is now a new solr core called otw-v2 with this field.
