### ISSUE TITLE
Add library label?

### ISSUE THREAD

**Issue by stuartlewis** [opentexts/opentexts#143]
I've had feedback from a few uers about adding back in the label for each search result that says which library the record is from.  The reasons seem to be two-fold:

1. It demonstrates immediatly that this is an aggregation site / search engine, as it shows there are results from different libraries.
2. It prepares the user for where they are about to go to when they click the link.  A first-time user may not realise they are going to jump out to another website, so this will hint towards that.

**Comment by sarahmonster** [comment]
I'm not opposed to this! I do think it should be relatively inconspicuous, though. What about something along these lines?

<img width="653" alt="Screenshot 2020-09-18 at 11 36 16" src="https://user-images.githubusercontent.com/376315/93588343-2bea9200-f9a3-11ea-9da9-12184bf9ba0b.png">
