### ISSUE TITLE
Export results feature: remove or reorder idLocal column

### ISSUE THREAD

**Issue by sarahmonster** [opentexts/opentexts#145]
From user feedback:

> Performed a search with 24k results, clicked download full results – it downloads into csv file and launched Mac Numbers. The largest central column was called idLocal which had no useful data – it should have been the Title Column.

If we could rename this column, that would probably be a good call.

**Comment by brizee** [comment]
I think the request should be to remove this column or re-order them.

The title column is currently the 3rd column whilst idLocal is 2nd, if ID's got long enough they'd start to push title off the right edge of the screen but idLocal is probably not useful to most people.
