### ISSUE TITLE
Export results: create unique file name

### ISSUE THREAD

**Issue by sarahmonster** [opentexts/opentexts#146]
From user feedback:

> The Download of all results – only creates a file called Data for every download, would be better to name it with the Search Name Used.  It someone is doing serious research it would be confusing and a pain.

Great point! It would be good to have a unique name for each file generated—maybe the search string, followed by any filters, followed by a datestamp?

**Comment by stuartlewis** [comment]
Could become a really long filename if filters are included (e.g. if a couple of languages and couple of libraries are included)?

How about the search term and a datestamp?

export-fish and chips-21092020-1445.csv?

export-<search string with special characters removed, just [a-zA-Z0-9]>-ddmmyyyy-hhmm.csv?
