### ISSUE TITLE
Write a privacy policy

### ISSUE THREAD

**Issue by sarahmonster** [opentexts/opentexts#151]
Since we're collecting user data, we'll need a privacy policy. 

We should include:
- What we do with feedback provided via Doorbell (especially where an email is provided, since that counts as personally identifiable data)
- What data we collect via Google (and a note that it's all anonymised!) see #112 
- Links to third-party privacy policities (ie, Doorbell and Google)

Reference:
https://www.privacypolicies.com/blog/privacy-policies-legally-required/#Privacy_Laws_In_The_Eu
Good example to follow: https://www.gov.uk/help/privacy-notice (we could go simpler than this!)

**Comment by stuartlewis** [comment]
I've committed a privacy policy now - a slightly stripped-down version of the gov.uk policy.  It could probably do with a wee bit of stlying, mainly because our CSS doesn't really do any rendering of lists. So assigning to @sarahmonster if that's ok? :)
