### ISSUE TITLE
Establish overall branding/look-and-feel of site

### ISSUE THREAD

**Issue by sarahmonster** [opentexts/opentexts#20]
[Style Tiles](http://styletil.es/) are mini-mood boards that reference site interface elements through font, color, imagery, buttons, and so on. 

The purpose of a Style Tile is get a sense of the overall look and feel of a visual design, without getting bogged down in finished elements or exact placements. Those will come later, once a design direction is chosen!

With that said, I've put together three different directions to choose from. They're all using open-source fonts, so we don't need to worry about licensing. The "logo" here is a placeholder—it's just an icon from the Noun Project—we'll probably want to think about something a bit more custom & unique here, but we can work on that as the overall visual brand progresses. 

For now, let's try to establish an overall direction, and then we can work on getting more of the details in place.

**Style tile A** is bright & friendly:
![friendly](https://user-images.githubusercontent.com/376315/85642126-769c8c80-b688-11ea-9751-f651665ac8d3.png)

**Style tile B** is light & open:
![open](https://user-images.githubusercontent.com/376315/85642128-78665000-b688-11ea-9fb0-d8b84d62a1c4.png)

**Style tile C** is more serious & academic:
![serious](https://user-images.githubusercontent.com/376315/85642129-78fee680-b688-11ea-8f38-5caf9317b91e.png)

@stuartlewis @gillhamilton I'd love to hear your thoughts here! Again, these are intended to establish an overall look-and-feel—they aren't final in any way, and they're a lot more colourful in condensed form than they will be when applied to a page, where we'll have more text and whitespace. 

- Which of these options best captures the look & feel you want the application to present?
- Is there anything that strikes you as out of place or awkward?
- Which of these is most likely to appeal to your core user? (Casual non-academics.) What about more users with more expertise? (Researchers & librarians.)

**Comment by helenwiles** [comment]
Hi Sarah! Helen here (UX intern at the Library)

We all had a quick discussion about this at the start of the week. While we liked elements from Style A and B the most, we agreed on **Style Tile B (light and open)** overall as we thought this fit the idea of being open and inclusive more than the other styles. We liked how clean and focused it was, and that it seemed more modern. We thought it appeared welcoming and simple to use, so would hopefully suit a wide range of audiences, and would be moving away from the more traditional 'academic' look that can sometimes be intimidating to some groups of people.

We did have a few things we would like to edit from Style B however (if this is feasible) - 
- Greyscale colours - while we liked the 'light' and 'neutral' feel of the colours, we just want to make sure the colour contrasts are complaint with WCAG guidelines and don't isolate anyone with vision deficiencies etc. If we can move away from the use of greys for the main bodies of text (especially the lightest tones) this would be great 
- Highlighting - if the style of highlighting search terms (used in Style A) could be used somewhat in Style B we think this could be an option to make it clearer. It's more a matter of preference (or to consider as an option further down the line)

Thanks again for all your work on this, Sarah!

**Comment by sarahmonster** [comment]
Thanks for the feedback! I've applied the style tile B (with edits) to the mockup, and here's the result:

Mockup A: https://www.sketch.com/s/893d4969-c396-4cb5-b898-a0ddb2ffded5/a/8GeED8/play

<div style="display: flex">
<img src="https://user-images.githubusercontent.com/376315/87035211-e9f1e280-c1e0-11ea-954f-c55f8205aa17.png" width="30%" />
<img src="https://user-images.githubusercontent.com/376315/87035223-ececd300-c1e0-11ea-914e-368c96f3c44a.png" width="30%" />
<img src="https://user-images.githubusercontent.com/376315/87035217-ebbba600-c1e0-11ea-8041-3ac7e345795d.png" width="30%" />
</div>

I wasn't quite sure if the typography was working so I tried a bit of a modification of the type + colour scheme as well, to see how that worked:

Mockup B: https://www.sketch.com/s/fc7e6aa4-6835-4fea-8ff5-94ce8ff9c653/a/YeDZZv/play

<div style="display: flex">
<img src="https://user-images.githubusercontent.com/376315/87035508-5967d200-c1e1-11ea-9dee-fe5be41381cb.png" width="30%" />
<img src="https://user-images.githubusercontent.com/376315/87035516-5c62c280-c1e1-11ea-920a-e7e8c7b09ed3.png" width="30%" />
<img src="https://user-images.githubusercontent.com/376315/87035513-5b319580-c1e1-11ea-9e06-25212638ed77.png" width="30%" />
</div>

They're both still a little bit rough, but should be sufficient to get a sense for how they'd work in practise. 

A few things to consider here:

1. Colour contrast: Everything here _should_ hit AA at the absolute minimum, although most of the text is also meeting AAA. If we need to meet AAA let me know and I'll be sure that's the case. 
2. Language support & typography: This may not be a problem at the moment, but we may want to think about how our chosen typography will support different languages. I've opted for open-source Google fonts here, but typically language support is limited. We can probably get the best language support by using native system fonts (plus a performance boost) at the cost of some "personality". This may be an acceptable trade-off (and, as a Mac user, I kind of love system fonts, but that's partly because the Mac ones are lovely!) and one I can design for, if we decide it makes sense to go that route.
3. Branding. We haven't really touched on this deeply, and I suspect it's going to be the best way to inject a wee bit of personality into the interface. The open book here is intended as a placeholder—it's really a bit too obvious. 😉 Let's discuss tomorrow.

**Comment by sarahmonster** [comment]
Last week, I presented a branding concept that I'm also sharing here for our records. 

## Context

From our discussions, we know that our branding needs to communicate the following:

1. The global nature of the service
2. A many-to-many connection (as opposed to one-to-one)
3. A service that is open & accessible to all

As I explored different concepts, I found that it was very easy to rely on visual cliches to communicate the concept—globes, eyes, books, trees—all of which felt rather too on-the-nose and obvious to be effective here (or they'd been so used in other applications as to be entirely unoriginal!)

Usually, I tend to present a few ideas to choose from, but I found that, in the time allotted, I'd only come to only one strong concept. Rather than presenting two weaker concepts alongside a stronger concept, I felt it was best to go all-in on the stronger concept, especially since this may not be a forever brand.

## Rationale 

The concept I selected is a constellation/series of data nodes, selected both for its abstraction (it can mean a number of different things) as well as for its clear communication of the many-to-many connection concept (there are literal nodes connected to other nodes). The constellation motif gives it a global/universal feeling, and the shape is open at one corner, indicating a willingness to embrace new members and contributions.

<img width="475" alt="Screenshot 2020-07-27 at 14 52 24" src="https://user-images.githubusercontent.com/376315/88550175-257e1080-d019-11ea-8bd8-54dfc3314904.png">

## Application

We can also go with a plainer wordmark, and consider adding the star texture in the background of the page instead:

<img width="479" alt="Screenshot 2020-07-27 at 14 55 41" src="https://user-images.githubusercontent.com/376315/88550252-3fb7ee80-d019-11ea-83b3-d7c5d4654955.png">

I'll likely iterate on this a bit as we apply the design to the page itself, so we don't necessarily need to make this decision immediately, just noting for context. 

Here's what this branding looks like when applied against our wireframes:

![front-page](https://user-images.githubusercontent.com/376315/88550422-80b00300-d019-11ea-8a52-dd40f67730e0.png)
![search-results](https://user-images.githubusercontent.com/376315/88550433-83aaf380-d019-11ea-9f5e-58e67d3ac12a.png)

There's a clickable prototype here: https://www.sketch.com/s/2878ffd7-1443-4e04-b984-753589b4cf31/a/YVyn1E/play

It's a bit of a shift from the styles above, but it stays in the same overall character whilst adding a bit more personality. 

If this branding seems appropriate and fitting for the project, we'll move forward with applying it to the site, with the caveat that there may be a wee bit more evolution that happens as it's applied to the site.

**Comment by sarahmonster** [comment]
I think we can close this now, since we're moving forward with this direction.
