### ISSUE TITLE
Feature request: visited links

### ISSUE THREAD

**Issue by stuartlewis** [opentexts/opentexts#204]
We've had a feature request from a user who is finding it hard to keep track of the links they have visited.  They suggested we number the results [1..10 etc] but I think this might not look good.

I notice that Google still use a different colour for visited links:

![image](https://user-images.githubusercontent.com/135022/101204260-db123d80-3663-11eb-9f93-eb69ea27a085.png)

Would this be a good option, and if so, any sugeestions for a nice complementary colour @sarahmonster ?

**Comment by sarahmonster** [comment]
Definitely agreed that a colour change would be a more predictable way of solving this particular user problem! I often tend to think of visited links as being unnecessary noise, but I think in the case of search engines they actually are quite useful to people—let's add them!

#205 has a suggested fix!
