### ISSUE TITLE
Add ability to export/download full results

### ISSUE THREAD

**Issue by sarahmonster** [opentexts/opentexts#21]
Suggested solution:

![search-results](https://user-images.githubusercontent.com/376315/85643291-9aad9d00-b68b-11ea-9dd4-ea096c50afef.png)

My thinking is it would make sense to position this as a secondary action underneath the primary ("load more") action below search results. Are we providing different data formats as well?

**Comment by stuartlewis** [comment]
First draft completed.  Export button prominently at the top:

![image](https://user-images.githubusercontent.com/135022/86891992-8e97f580-c0f7-11ea-9fc8-4d35eab45c00.png)

It would be good to expand this in the future.  At present it just triggers a CSV download (limited to 5,000 rows).  Other file formats could be possible, along with selecting other options, so maybe bounce to an export page to select these, then trigger the export.

**Comment by sarahmonster** [comment]
This looks good to me! I've moved it below the "load more" button so it's not a primary action (since it won't be useful for _all_ users):

<img width="674" alt="Screenshot 2020-08-10 at 14 00 26" src="https://user-images.githubusercontent.com/376315/89785162-da342980-db11-11ea-9500-7b2fba98cebe.png">

I'm going to close this issue, but if we want to expand on the functionality, we can open a new issue to track that! It would be good to get an idea of how people use to export functionality & the data in order to see how we could customise their exports.
