### ISSUE TITLE
Extend feedback mechanism to ask if users found what they're looking for

### ISSUE THREAD

**Issue by sarahmonster** [opentexts/opentexts#4]
Currently, the feedback mechanism looks like this:

<img width="428" alt="Screenshot 2020-06-25 at 00 39 44" src="https://user-images.githubusercontent.com/376315/85637905-6383bf80-b67c-11ea-8954-a67e538ce0ce.png">

I'd recommend a small change to ask slightly more directed questions. Since our primary aim is to find out if someone has found what they’re looking for, let’s focus on that as the primary question, and then leave an open text box for anything else they’d like to share. 

![feedback-popover](https://user-images.githubusercontent.com/376315/85142282-03d28200-b240-11ea-9a01-f6c2e12afa7d.png)

All fields should be optional. We should only request an email address if we plan to respond to queries—I haven't included it here but if the plan is to respond to users and/or ask follow-up questions, then it's worth including, but making it a non-required field. 

We should avoid using placeholders as labels if at all possible, since this presents [issues for both accessibility and usability](https://www.nngroup.com/articles/form-design-placeholders/). We'll also want to style the popover and the form once we've established our overall styles for the site.

Ideally, this data should be collated with their search term, so we can follow up and figure out why the result didn’t return anything helpful!

**Comment by stuartlewis** [comment]
The doorbell.io configuration isn't too rich and powerful to add new fields like this unfortunately.

![image](https://user-images.githubusercontent.com/135022/85975959-4d099b00-b9d1-11ea-8dcd-040576d1dee1.png)

This is the best I can do (without swapping to another tool).

**Comment by sarahmonster** [comment]
I'd actually say this totally does the trick! We'll want to customise the styling to match the site, but this structure makes sense to me and still allows for slightly more directed feedback. 👍
