### ISSUE TITLE
file_get_contents() for svgs doesn't seem to work properly in CodeIgniter?

### ISSUE THREAD

**Issue by sarahmonster** [opentexts/opentexts#56]
I tried to use `file_get_contents` to inline svgs but ran into some CodeIgniter issues, so I wound up just using `include` directives instead. I'm not sure if this will have security or other repurcussions, so I wanted to make a note of it in case there's an easy workaround here. Feel free to close if this just isn't a concern. 

This [CSS Tricks article](https://css-tricks.com/using-svg/) seems to indicate that `file_get_contents` is the correct function to use, not from a security perspective, but from a functionality perspective, but maybe that isn't an issue so long as SVGs are properly encoded. (Still a bit more fragile than it might strictly need to be...)

**Comment by stuartlewis** [comment]
Where in the code is that bring used? I'll try it on my version

**Comment by sarahmonster** [comment]
Here's an example of where I was trying to use it: https://github.com/opentexts/opentexts/blob/6ffaedd4137b028848f87e0362c975038017cada/app/Views/templates/search-header.php#L8

I wound up using `include()` instead because `file_get_contents()` seemed to be giving an error, but apparently `file_get_contents()` would be a more resilient function to use. Not a huge deal (I don't _think_?), but if we can remedy it, things might be a little more bulletproof.

**Comment by brizee** [comment]
Had a quick look, I reckon this is just a path issue. `include()` looks for files relative to the current script (i.e. `search-header.php` in this case) whilst `file_get_contents()` looks for files relative to the current working directory (relative to `public/index.php` in this case)

So couple of ways of tackling this:
1. Use `echo file_get_contents('../app/Views/templates/svg/menu.svg');`
2. Move the svg folder into the public folder

**Comment by stuartlewis** [comment]
Let's do number two (move svg into the public folder). 

This feels slightly better from a security point of view, and as the SVG may want to be referenced directly one day, having it there serves that purpose also.

**Comment by sarahmonster** [comment]
That was a much simpler fix than I'd expected—thank you! I'll be sure to put future SVGs in the public folder as well. 👍
