### ISSUE TITLE
Design & implement a site footer

### ISSUE THREAD

**Issue by sarahmonster** [opentexts/opentexts#57]
Right now, there's a standard footer on every page:

<img width="1031" alt="Screenshot 2020-08-10 at 13 04 21" src="https://user-images.githubusercontent.com/376315/89780793-0481e900-db0a-11ea-8239-631d73f21e16.png">

We may want to think about the content that we include in this footer area. What content should be included here?

Some top-of-mind suggestions:

- privacy policy
- accessibility statement
- link to GitHub repository
- links to main content pages (home, about, get involved, help)
- brief one- or two-line text to explain what the project is about
- copyright statement?

Is there anything else we might want to include here?

@stuartlewis @gillhamilton

**Comment by sarahmonster** [comment]
Hathi Trust is probably a good example here in terms of content—they're using a lot of the items suggested above:

<img width="1009" alt="Screenshot 2020-08-26 at 15 34 21" src="https://user-images.githubusercontent.com/376315/91317200-a879be80-e7b1-11ea-90fb-fc3d359953de.png">

**Comment by stuartlewis** [comment]
If we have most of this content in the footer, do you think we culd remove the burger and menu items from the header bar, or do we still need some of those links duplicated up there?

Links to include:
- Your list seems pretty comprehensive
- Probably don't need the github link (could maybe add that in the 'about' page? It won't be relevant to most users)
- We don't really have anything like a privacy policy defined yet, but as long as it is easy to make new pages and add them to the footer (which it will via the footer template) than that's fine and we can adjust as the site evolves, particulalry on the policy side of things.

**Comment by sarahmonster** [comment]
> do you think we culd remove the burger and menu items from the header bar, or do we still need some of those links duplicated up there?

I've keep batting this one back and forth in my head—in theory, no, but in practise, I think it's best to provide users with links where they can easily reach them and expect to see them. I'm generally not a big fan of hamburger menus at desktop sizes, but I actually think it makes sense here where the site navigation isn't the primary interaction, but it's still important enough that you'd want users to be able to easily access the pages.

I'm also thinking that we should show the search header, or at least some way of accessing the search directly, on all the static pages—otherwise you need to return to the homepage to run a search, which is an awkward interaction. I'm going to work on improving the navigation at the weekend, and hopefully that can iron out some of these usability problems.
