### ISSUE TITLE
Display the current number of result set

### ISSUE THREAD

**Issue by sarahmonster** [opentexts/opentexts#58]
The [x-100] here is a placeholder. We should replace it with an actual value that's representative of the actual results being shown, so that users can tell where they are in the results being returned.

<img width="253" alt="Screenshot 2020-08-10 at 13 11 14" src="https://user-images.githubusercontent.com/376315/89781302-faacb580-db0a-11ea-8317-7a60cd61b6be.png">

This will work in concert with the "more results" button.

**Comment by brizee** [comment]
I've done a quick pass on this already will wait til we've settled #59 before finishing and setting up a PR though
