### ISSUE TITLE
"More results" button needs to hooked up to more results

### ISSUE THREAD

**Issue by sarahmonster** [opentexts/opentexts#59]
To simplify the user experience, I've removed the navigation in favour of a single "more results" button. (The rationale being that, in searching, you very rarely want to navigate through pages of less relevant search results.... you just want to load more until you find whatever it is you want, so we really just need a button that accomodates that single behaviour.)

<img width="253" alt="Screenshot 2020-08-10 at 13 11 14" src="https://user-images.githubusercontent.com/376315/89781302-faacb580-db0a-11ea-8317-7a60cd61b6be.png">

So! We've got the button, we just need to hook it up.

Probably worth addressing in concert with #58, which shows the number of the currently-displayed result set.

**Comment by stuartlewis** [comment]
Would you see this reloading the whole page (but now with (e.g.) 20 results instead of 10), or just inserting more records on the currently loaded page?

**Comment by brizee** [comment]
I don't think the UX in the former would be desirable here, if the page reloads but all the content above the fold is identical it's going to confuse a user.

Sadly, might be mistaken but doesn't look like we're in a strong place to tackle the latter approach just now though it might be something worth working towards?

In any case if we're just fetching more content I'm not sure if the control in #58 is still desirable? We probably just need a "No more results" display?

**Comment by brizee** [comment]
Forgot to mention it here but discussed this with @sarahmonster and she was leaning towards loading in the content on the same page without a reload. I've pushed up a branch that moves the creation of results into Javascript.  Lots of refactoring still to do but this seems like the best way to achieve this and also the seamless reloading of results requested for multi-filtering as discussed in #13
