### ISSUE TITLE
Get Involved page: copyedit & improve design

### ISSUE THREAD

**Issue by sarahmonster** [opentexts/opentexts#6]
Let's make a single "Get involved" page to cover the current [contribute data](https://opentexts.world/contribute) page. 

The current page could be a bit more user-friendly (that chart might be intimidating to some)—I'm thinking maybe some more background information about who can get involved might help? How can we best use this page to encourage people to get involved... and are there ways of helping out other than providing data?

Let brainstorm!

**Comment by sarahmonster** [comment]
Once we have solid copy, I can do some work on the design side to make it more legible & easier to use. (I'll do this with all of the static pages!)

**Comment by stuartlewis** [comment]
Thinking about this more... I'm not sure generally how much scope there is for people to get involved (outside of the scope of the STA work that we're really glad @sarahmonster and @brizee are helping out with!). The page really is much more about become a data contributor, designed for library data teams, and is written that way.  We should probably change the page title in the header bar to this?
