### ISSUE TITLE
Help page: expand content & improve design

### ISSUE THREAD

**Issue by sarahmonster** [opentexts/opentexts#7]
Right now, it's not particularly helpful. 😉 

https://opentexts.world/support

User feedback will also help to inform this section. Once there's a content structure, I can look into how the design can best support that content.

**Comment by sarahmonster** [comment]
I'm going to start labelling any issues that bring up issues we'll probably want to explain in a bit more detail on the help page with an [add-to-help-page](https://github.com/opentexts/opentexts/issues?q=label%3Aadd-to-help-page+) label, so we can more easily find & track them. I expect this label will collect more issues as we start testing the site.

Off the top of my head, we'll probably also want to explain:
- how to search
- how to use filters
- different file formats available
- how to download a dataset from a search
- who to contact if you run into issues

**Comment by stuartlewis** [comment]
Thanks Sarah.  Shall I start by writing one long set of help topics, and then you can take a look from a design point of view to work out how to bust structure it and split it up (if splitting up is required)?

**Comment by sarahmonster** [comment]
Yes, that sounds like an excellent approach! I anticipate we'll go with a long scrolling page sort of deal here, but we'll definitely let the content dictate that. I expect it'll be something of an ongoing work in progress, especially as testing & actual usage brings up additional topics to add.

**Comment by stuartlewis** [comment]
Ready for @sarahmonster to work on. Thanks! 🥇
