### ISSUE TITLE
Improve icons for file types

### ISSUE THREAD

**Issue by sarahmonster** [opentexts/opentexts#76]
Right now, we're showing a small collection of icons to indicate different file types available for download:

<img width="620" alt="Screenshot 2020-08-24 at 19 31 22" src="https://user-images.githubusercontent.com/376315/91082361-7c8afb80-e640-11ea-86b8-d665305e058d.png">

In order, that's:
- .pdf
- .json
- .txt

I think we can do a little bit here to improve these icons—make them more consistent with one another, and make their intentions clearer.

Off the top of my head:

- Use a similar icon for each
- Use a single colour, so they don't demand quite as much attention
- Use text and an icon to signify the file type
- Implement ALT text and/or titles or tooltips, so it's clear what's happening

Here's a quick mockup for what that might look like:

<img width="345" alt="Screenshot 2020-08-24 at 20 16 34" src="https://user-images.githubusercontent.com/376315/91086455-ddb5cd80-e646-11ea-91d1-ba53be005a1c.png">

These will need some refinement to ensure that they're legible at small sizes and optically balanced, but if this feels like a useful direction I can

We should also be sure to use ALT text for the icons, so they're accessible to everyone. This might be a case where a tooltip or a title attribute is helpful to provide more context to users before they click on the icons as well. 

Alternatively, we could drop the icons entirely and switch to a text-based approach. Something like this:

<img width="612" alt="Screenshot 2020-08-24 at 20 27 36" src="https://user-images.githubusercontent.com/376315/91087383-43568980-e648-11ea-9c1c-25570a087603.png">

This would make the meaning a bit more explicit, although potentially add more noise to the actual listings themselves.

What do you think, @stuartlewis?

**Comment by brizee** [comment]
Quick point of clarity, the last entry there isn't a TXT according to Solr, it's Other (it can also be more than one URL). The most common usage I've seen is a txt but other formats might exist in the database.

So we should probably actually have an Other icon - alternatively we could try and match the file extension to an icon (i.e. if the url ends with .txt then use the TXT icon) and have an Unknown icon if we can't detect the file type?

**Comment by stuartlewis** [comment]
To add complexitry, we're likely to add a few more (which will require new optional fields in the data feeds).

- One for plain text (just the raw text from the scanned item)
- One for ALTO-XML (raw text in XML format, with bounding boxes for each word so you know where it is on the page)

The IIIF icon is JSON, however it isn't the fact that it is JSON whih is import, but that it is what's known as a IIIF manifest file. See: [https://iiif.io/](https://iiif.io/)

The icon can be dragged from your browser into a viewer, for example drag one of the icons (find one by doing a search and restricting to the Wellcome Trust Library) into the viewer halfway down this page: [https://iiif.harvard.edu/mirador-viewer/](https://iiif.harvard.edu/mirador-viewer/).

I agree it would be good to standardise the logos, but the IIIF one is sort-of becoming well known so would be good to keep it as it is if possible.

**Comment by sarahmonster** [comment]
Oh, how interesting! There's a lot more here than I'd originally thought—thanks for the additional context!

I'm going to mark this as "add-to-help-page" since I think this could warrant a wee bit of explanation, although ideally we'll build out the UI in such a way that makes it obvious. 

So! Let's focus on getting the data right first:
- Add a field for .txt files (plain text)
- Add a field for alto-xml
- Keep IIIF rather than JSON
- Add a section to the help page about file types & how to use them

Given the possibly large number of file types here, I wonder if it wouldn't be best to just use plain-text labels here, rather than icons. I like the icons visually, but ultimately text labels will be more accessible and usable here, especially where we're likely to have a longer string of labels and the icons may become harder to distinguish from one another. (As it is, they kind of require text labels inside the icons in order to be truly usable.)

**Comment by stuartlewis** [comment]
Thanks.  I'll look at addressing some of this in the help and contribute pages.

In the longer term, it would be good to add an additional filter, so that a user can select to see, for example, only results where there is a PDF, or where there is a IIIF manifest.

**Comment by sarahmonster** [comment]
Agreed! I filed an issue so we wouldn't forget, but I've attached it to the nebulous "Future" milestone since it's not launch-critical.

**Comment by brizee** [comment]
The trick here is definitely going to be the other links? We can't guarantee that we'll know what type the data is there (I believe) so we can't put a correct icon and a generic label is probably going to look worse? Alternatively could we just migrate the URLs we know the type of to separate fields and not display Other URLs?

**Comment by stuartlewis** [comment]
Yes - we definitly need to split out the file types into other separate solr fields (e.g. urlPDF, urlIIIF, urlALTOXML, urlPLAINTEXT, etc).  I'll have a go at this, but it might require the re-processing and re-loading of all data (a chore, but not too painful). The alternative is to store them in pairs but all in the same 'link' field, e.g. "type=pdf;link=http://www.example.com/file.pdf", but I think that would be more painful to process on the client side.

To offer the filters, I think this information shuld be enough, we don't need to add extra 'hasPDF, hasIIIF, etc' fields. See: [https://stackoverflow.com/questions/10722145/solr-how-do-i-construct-a-query-that-requires-a-not-null-location-field](https://stackoverflow.com/questions/10722145/solr-how-do-i-construct-a-query-that-requires-a-not-null-location-field) as an example of how to find non empty fields. I've not looked to see if this can be turned into a filter per se rather than a search parameter.
