### ISSUE TITLE
Animate logo on hover

### ISSUE THREAD

**Issue by sarahmonster** [opentexts/opentexts#83]
This is definitely non-critical, but would be a nice touch to add if we've time. (I'm thinking something very subtle, like a slight rotation or similar, but am open to suggestions! Moving the points could be nice, but definitely more complex to make work.)

**Comment by brizee** [comment]
It's technically simple enough to be redone in a HTML5 canvas I reckon, from there we could do some more complex animation quite cheaply... for sure it's polish work at that stage though :)

**Comment by stuartlewis** [comment]
Included in #120
