### ISSUE TITLE
Suggestion: should we show suggested searches on homepage?

### ISSUE THREAD

**Issue by sarahmonster** [opentexts/opentexts#85]
I had this in my "list of things to file as issues eventually" so I thought I'd make a note of it now, although I'm not sure it's strictly required.

I like the simplicity of the current homepage, but we might want to consider adding suggested searches or similar, for users who maybe want to browse books available but aren't sure what to search for.

User testing & feedback will likely inform this to some degree, but it could be helpful to provide some suggested search terms, or ways of exploring the dataset if you're in more of a browsing mood than a searching mood, or you don't know explicitly what you're looking for.

**Comment by stuartlewis** [comment]
I would be tempted to add these now if we can?  I think the site on one hand is easy to use (just stick some text in the box and hit search), but to really get some value from it, showing a few examples of what a more defined search could look like, might help.

I've assigned to myself to start thinking about what might be good examples to include.

**Comment by sarahmonster** [comment]
Makes sense to me! Let's handle this in the "Polish" milestone, and you can assign over to me once we're ready for the design side of things. 🙂

**Comment by brizee** [comment]
I was wondering if recent searches might also be useful? If we're already javascript based it'd be easy to save query details into local storage so when you visit the site again it can remind you of any searches you've made in the last couple of days - in case you want to pick them up again? 

Potentially this can be moulded into one single design element - showing more suggestions if you have less history and vice versa.

**Comment by stuartlewis** [comment]
Tricky one to know where to start! Here's a few very random thoughts to capture a variety of subjects:

- [Medical reports from London](https://opentexts.world/search?q=medical+report+london)
- [Volcanoes in New Zealand](https://opentexts.world/search?q=new+zealand+volcanoes)
- [Recipe books](https://opentexts.world/search?q=recipe+book)
- [A midsummer night's dream](https://opentexts.world/search?q=a+midsummer+night%27s+dream)
- [Joke books](https://opentexts.world/search?q=joke+book)
- [Greek antiquities dictionary](https://opentexts.world/search?q=greek+antiquities+dictionary)
- [Love poems] (https://opentexts.world/search?q=love+poems)

@gillhamilton will probably have lots of good ideas too.
