### ISSUE TITLE
Pro User Search features

### ISSUE THREAD

**Issue by brizee** [opentexts/opentexts#90]
Solr is pretty flexible in how it handles searches which allows us to offer some advanced tools as per #89 - from a UX perspective a nice extension to this would be to offer some of the more well known "pro user" features from search engines. Some examples from a [random site](https://www.lifehack.org/articles/technology/20-tips-use-google-search-efficiently.html):

`"Edinburgh witches"` - Putting several words in quotes means that the exact phrase is searched for rather than each word independently
`-warlocks` - Putting a hyphen or subtract sign at the start of a term should exclude results including that term
`site:nls.uk` - Filters down to a particular website, instead of applying to a site `year:1500-1800` strikes me as a really useful tool

All of this functionality should be replicated in the advanced search form but by allowing for these short hands you make the tool easier to use with fewer clicks for more advanced users.

**Comment by stuartlewis** [comment]
Double quotes around a string (e.g. ["cheshire cheese"](https://design.opentexts.world/search?q=%22cheshire+cheese%22)) already works.

Removing a term with a minus seems to be default behaviour too: (e.g. ["cheshire cheese" -ook)](https://design.opentexts.world/search?q=%22cheshire+cheese%22+-ook)

`year:1500-1800` would also be good. I think the challenge would be parsing this out into the right filter query (identifying a field and then matching it and constructing the solr query). My personal preffered method (and I know many others disagree on this!) is to start with a broad simple search, and then for filters to use filters / facets once I see what data looks like (e.g. are there actually any records from 1500-1800 or not).

We can definitly document these options in the help page as you suggest. Thanks!

**Comment by brizee** [comment]
Yeah, this issue probably makes more sense in the context of #91 😄 - some of the default options are pretty intuitive and unlikely to confuse new users but some could - so I think we should start from an assumption of disabling all of the custom operators then work back and try to determine which ones are both:
* Helpful to power users
* Unlikely to hinder beginner users (i.e. by being accidentally used and lowering the quality of their results)

So quotes and minus are good inclusions but maybe tilde and slashes (regex) are not.

Speaking of regex I'd consider that the solution to the year filter [/year: ?([0-9]{2,4})(?:-([0-9]{2,4}))?/](https://regex101.com/r/xx9gJT/1/) should do it

**Comment by sarahmonster** [comment]
Some related user feedback here:

> Specific searches threw up more than expected , maybe misunderstanding of the search engine ? ‘George Orwell’+ 1984 provides many more results than expected. A one-word search e.g. Orwell yields a mix of the things to do with the place Orwell, books by the author George Orwell and books where Orwell is mentioned. When you add George to search George Orwell you don’t get all George + Orwell items first it just seems a haphazard mix and Orwell only results are mixed in with George + Orwell. Would it be either an option or just a hard-wired practice to list first Orwell where Orwell is the author, then where Orwell occurs in the title of a book, then Orwell when mentioned in a book. Where one has George + Orwell surely the combination of both should be listed first.

I suspect people are going to try Google-style searches here (note: I have no idea what these are or how to use them, so they're probably a pro-level feature!) so it would be good to follow that model whenever we implement this. We'll also want to add instructions to the help page (#7), which I am happy to help with because if I can understand it, probably anyone can. 😜

**Comment by brizee** [comment]
I've split part of this feedback into #153 as I think this also applies.
